version: '3.9'

services:
  db:
    image: mysql:8.0.22
    command: ["--character-set-server=utf8mb4",  "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password", "--lower_case_table_names=1"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: note_app
      MYSQL_USER: note_app
      MYSQL_PASSWORD: note_pass
    volumes:
      - ./scripts/database:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
